package com.satecho.agrosafe.platform.apiservice.agronomist.application.queryservices;

import com.satecho.agrosafe.platform.apiservice.agronomist.domain.model.aggregates.Recommendation;

import java.util.List;
import java.util.Optional;

/**
 * Service interface for handling query operations related to recommendations.
 */
public interface RecommendationQueryService {
    /**
     * Retrieves a recommendation by its identifier.
     *
     * @param id the recommendation identifier
     * @return an Optional containing the Recommendation if found, or empty if not
     */
    Optional<Recommendation> findById(Long id);

    /**
     * Retrieves all recommendations generated for a specific farmer user.
     *
     * @param farmerUserId the identifier of the farmer user
     * @return a List of Recommendation aggregates
     */
    List<Recommendation> findByFarmerUserId(Long farmerUserId);

    /**
     * Retrieves all recommendations generated by a specific agronomist user.
     *
     * @param agronomistUserId the identifier of the agronomist user
     * @return a List of Recommendation aggregates
     */
    List<Recommendation> findByAgronomistUserId(Long agronomistUserId);
}
