package com.satecho.agrosafe.platform.apiservice.agronomist.infrastructure.persistence.jpa.repositories;

import com.satecho.agrosafe.platform.apiservice.agronomist.infrastructure.persistence.jpa.entities.RecommendationPersistenceEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * JPA Repository for {@link RecommendationPersistenceEntity} database operations.
 * <p>
 * This interface handles direct database queries and CRUD operations for agronomist recommendations.
 * </p>
 */
@Repository
public interface RecommendationPersistenceRepository extends JpaRepository<RecommendationPersistenceEntity, Long> {

    /**
     * Retrieves all recommendations associated with a specific farmer user, ordered by generation timestamp in descending order.
     *
     * @param farmerUserId the ID of the farmer user
     * @return a list of recommendation persistence entities
     */
    List<RecommendationPersistenceEntity> findByFarmerUserIdOrderByGeneratedAtDesc(Long farmerUserId);

    /**
     * Retrieves all recommendations generated by a specific agronomist user, ordered by generation timestamp in descending order.
     *
     * @param agronomistUserId the ID of the agronomist user
     * @return a list of recommendation persistence entities
     */
    List<RecommendationPersistenceEntity> findByAgronomistUserIdOrderByGeneratedAtDesc(Long agronomistUserId);
}
