package com.satecho.agrosafe.platform.apiservice.agronomist.application.internal.queryservices;

import com.satecho.agrosafe.platform.apiservice.agronomist.application.queryservices.RecommendationQueryService;
import com.satecho.agrosafe.platform.apiservice.agronomist.domain.model.aggregates.Recommendation;
import com.satecho.agrosafe.platform.apiservice.agronomist.domain.repositories.RecommendationRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * Implementation of the {@link RecommendationQueryService} interface.
 * Handles query operations related to recommendations.
 */
@Service
public class RecommendationQueryServiceImpl implements RecommendationQueryService {

    /**
     * Repository for accessing recommendation data.
     */
    private final RecommendationRepository recommendationRepository;

    /**
     * Constructs a {@code RecommendationQueryServiceImpl} with the specified repository.
     *
     * @param recommendationRepository the repository for managing recommendations
     */
    public RecommendationQueryServiceImpl(RecommendationRepository recommendationRepository) {
        this.recommendationRepository = recommendationRepository;
    }

    /**
     * Retrieves a recommendation by its identifier.
     *
     * @param id the recommendation identifier
     * @return an Optional containing the Recommendation if found, or empty if not
     */
    @Override
    public Optional<Recommendation> findById(Long id) {
        return recommendationRepository.findById(id);
    }

    /**
     * Retrieves all recommendations generated for a specific farmer user, ordered by generation date descending.
     *
     * @param farmerUserId the identifier of the farmer user
     * @return a List of Recommendation aggregates
     */
    @Override
    public List<Recommendation> findByFarmerUserId(Long farmerUserId) {
        return recommendationRepository.findByFarmerUserIdOrderByGeneratedAtDesc(farmerUserId);
    }

    /**
     * Retrieves all recommendations generated by a specific agronomist user, ordered by generation date descending.
     *
     * @param agronomistUserId the identifier of the agronomist user
     * @return a List of Recommendation aggregates
     */
    @Override
    public List<Recommendation> findByAgronomistUserId(Long agronomistUserId) {
        return recommendationRepository.findByAgronomistUserIdOrderByGeneratedAtDesc(agronomistUserId);
    }
}
