package com.satecho.agrosafe.platform.apiservice.agronomist.infrastructure.persistence.jpa.entities;

import com.satecho.agrosafe.platform.apiservice.agronomist.domain.model.valueobjects.RecommendationPriority;
import com.satecho.agrosafe.platform.apiservice.agronomist.domain.model.valueobjects.RecommendationStatus;
import com.satecho.agrosafe.platform.apiservice.shared.infrastructure.persistence.jpa.entities.AuditableAbstractPersistenceEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

/**
 * Persistence entity representing an agronomist recommendation in the database.
 * <p>
 * This class maps the {@code recommendations} table and stores suggestions, actions, and priority
 * levels generated by an agronomist for a farmer.
 * </p>
 */
@Entity
@Table(name = "recommendations")
@Getter
@Setter
@NoArgsConstructor
public class RecommendationPersistenceEntity extends AuditableAbstractPersistenceEntity {
    
    /**
     * The ID of the agronomist user who generated the recommendation.
     */
    @Column(name = "agronomist_user_id", nullable = false)
    private Long agronomistUserId;
    
    /**
     * The ID of the farmer user for whom the recommendation is intended.
     */
    @Column(name = "farmer_user_id", nullable = false)
    private Long farmerUserId;
    
    /**
     * The ID of the farm zone associated with this recommendation.
     */
    @Column(name = "zone_id")
    private Long zoneId;
    
    /**
     * The title of the recommendation.
     */
    @Column(name = "title", nullable = false, length = 200)
    private String title;
    
    /**
     * The detailed description of the recommendation.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    /**
     * The recommended actions or steps to be performed by the farmer.
     */
    @Column(name = "recommended_actions", columnDefinition = "TEXT")
    private String recommendedActions;
    
    /**
     * URL link to any attached document, image, or resource.
     */
    @Column(name = "attachment_url", length = 500)
    private String attachmentUrl;
    
    /**
     * The priority level of the recommendation (e.g., LOW, MEDIUM, HIGH).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false, length = 20)
    private RecommendationPriority priority;
    
    /**
     * The status of the recommendation (e.g., PENDING, RESOLVED).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private RecommendationStatus status;
    
    /**
     * The timestamp indicating when the recommendation was generated.
     */
    @Column(name = "generated_at", nullable = false)
    private Instant generatedAt;
    
    /**
     * The timestamp indicating when the recommendation was resolved or addressed.
     */
    @Column(name = "resolved_at")
    private Instant resolvedAt;
}
